### ISSUE TITLE
观看直播聊天用户不显示昵称 只显示uid怎么解决啊

### ISSUE THREAD

**Issue by BoGeLi** [zhaoyang21cn/ILiveSDK_iOS_Demos#10]

**Comment by wilderliao1** [comment]
如果用的是 ILVLiveTextMessage 发送文本消息，那么只有在收到消息之后根据id获取到用户的详细资料，再显示昵称。
如果用的是 ILVLiveCustomMessage 发送自定义消息，那么可以利用ILVLiveCustomMessage里面的data字段将昵称传进去。
