### ISSUE TITLE
随心播demo中直播列表请求到的数据一直为空

### ISSUE THREAD

**Issue by dudwchina** [zhaoyang21cn/ILiveSDK_iOS_Demos#3]
[LiveListRequest] Post Json : {
    appid = 1400019301;
    pageIndex = 0;
    pageSize = 50;
}
reqest url = http://182.254.234.225/sxb/index.php?svc=live&cmd=list

 [LiveListRequest] request's responseString is :

================================
 {"errorCode":0,"errorInfo":"","data":{"totalItem":"0","recordList":[]}}

**Comment by wilderliao1** [comment]
你好，请更新下最新的随心播，我们已经替换独立模式的server，appid更换为1400019352。
