### ISSUE TITLE
这个DEMO你们都不自己跑一下吗？

### ISSUE THREAD

**Issue by clg456852** [zhaoyang21cn/ILiveSDK_iOS_Demos#4]
到处在赋值只读属性，什么鬼？

**Comment by kennethmiao** [comment]
是随心播还是简单直播demo，麻烦把有问题的地方贴一下，我们看下

**Comment by wilderliao1** [comment]
这个应该是更新了sdk，没有及时更新demo导致的，由于前期版本的sdk迭代非常的快，导致的不同步，现在已经放缓节奏。
