### ISSUE TITLE
setAVRootView这里会崩

### ISSUE THREAD

**Issue by olizax** [zhaoyang21cn/ILiveSDK_iOS_Demos#6]
ILIveSDK: 1.1.2
TILiveSDK:1.0.3
OS:10.2
iPhone 6P
CODE:

- (void) StartLive{
    ILiveRoomOption *option = [ILiveRoomOption defaultHostLiveOption]; //默认主播配置
    TILLiveManager *manager = [TILLiveManager getInstance];
    [manager setAVRootView:self.view]; //设置渲染承载的视图
    //[manager addAVRenderView:self.view.bounds forKey:self.host]; //添加渲染位置
    [manager addAVRenderView:self.view.bounds forIdentifier:@"10001" srcType:QAVVIDEO_SRC_TYPE_CAMERA];
    
    [manager createRoom:31234 option:option succ:^{
        NSLog(@"创建房间成功");
    } failed:^(NSString *moudle, int errId, NSString *errMsg) {
        NSLog(@"创建房间失败");
    }];
}

LOG:
Jan 13 21:02:36  LiveTest[25260] <Error>: CGContextDrawImage: invalid context 0x0. Backtrace:
	  <-[AVGLShareInstance getImageData:]+192>
	   <-[AVGLShareInstance setuploadingImage]+136>
	    <-[AVGLShareInstance initOpenGL]+28>
	     <-[AVGLBaseView initOpenGL]+48>
	      <-[ILiveGLBaseView initWithFrame:]+400>
	       <-[ILiveGLBaseView initWithFrame:currentUserID:]+84>
	        <+[ILiveGLBaseView createRenderView:currentUserID:]+232>
	         <-[ILiveRoomAVManager createGLViewIn:atRect:]+520>
	          <-[ILiveRoomAVManager createGLViewIn:]+76>
	           <-[ILiveRoomManager createGLViewIn:]+84>
	            <-[TILLiveManager setAVRootView:]+88>
	             <-[ViewController StartLive]+152>
	              <-[ViewController onClick:]+148>
	               <<redacted>+96>
	                <<redacted>+80>
	                 <<redacted>+452>
	                  <<redacted>+584>
	                   <<redacted>+2484>
	                    <<redacted>+2988>
	                     <<redacted>+340>
	                      <<redacted>+2736>
	                       <<redacted>+784>
	                        <<redacted>+24>
	                         <<redacted>+524>
	                          <<redacted>+804>
	                           <CFRunLoopRunSpecific+444>
	                            <GSEventRunModal+180>
	                             <<redacted>+684>
	                              <UIApplicationMain+208>
	                               <main+124>
2017-01-13 21:02:37.094319 LiveTest[25260:9093666] Error loading shader: The file name is invalid.

**Comment by kennethmiao** [comment]
other link 加上 -ObjC
