### ISSUE TITLE
什么时候可以出个稳定版本啊

### ISSUE THREAD

**Issue by BoGeLi** [zhaoyang21cn/ILiveSDK_iOS_Demos#9]
rt 谢谢

**Comment by kennethmiao** [comment]
遇到什么问题了可以反馈一下

**Comment by BoGeLi** [comment]
就是感觉demo一直在改 好多接口也变了 bug也修复了好多 就想问下 我们打算上线看看啥时候版本稳定了 现在sdk都是beta的

**Comment by kennethmiao** [comment]
demo只是展示sdk调用的其中一种流程，具体还是以贵公司的业务为主。sdk经过多个版本的迭代，性能优化了很多，已经有很多上线的app了，请放心使用。使用过程有什么问题或者有什么建议，麻烦反馈给我们。

**Comment by BoGeLi** [comment]
哦 好哒
